name: vnegnn
channels:
  - defaults
  - conda-forge
dependencies:
  - biopython==1.78
  - rdkit==2023.03.3
  - pymol-open-source==2.5.0
  - python-lmdb==1.4.1
  - openbabel==3.1.1
  - pip
  - pip:
      - lightning==2.2.1
      - wandb==0.16.1
      - hydra-core==1.3.2
      - hydra-colorlog==1.2.0
      - hydra-submitit-launcher==1.2.0
      - einops==0.7.0
      - fair-esm==2.0.0
      - pandas==2.1.4
      - python-dotenv==1.0.1
      - gradio==4.20.1