defaults:
  - _self_
  - optimizer: adamw 
  - lr_scheduler: reduce_lr_on_plateau

_target_: src.models.egnn.CoVNEGNNClassifier
input_features: 1280
node_features: 100
edge_features: 1
hidden_features: 100
out_features: 100
num_layers: 5
act:
  _target_: torch.nn.SiLU
  _partial_: true
optimizer: ${optimizer}
lr_scheduler: ${lr_scheduler}
batch_size: ${batch_size}
dropout: 0.1
segmentation_loss:
  _target_: src.utils.losses.DiceLoss
segmentation_loss_weight: 1.0
global_node_pos_loss:
  _target_: src.utils.losses.PositionMinGlobalNodeHuberLoss
global_node_pos_loss_weight: 1.0
node_aggr:
  _target_: torch_geometric.nn.MeanAggregation
  _partial_: true
cord_aggr:
  _target_: torch_geometric.nn.MeanAggregation
  _partial_: true
dcc_threshold: 4
residual: true
norm_coords: true
norm_coors_scale_init: 0.01
norm_feats: true
number_of_global_nodes: ${number_of_global_nodes}
initialization_gain: 1.0
scaling_factor: 5
confidence_loss_weight: 1
confidence_gamma: 4.0
weight_share: false
tau: ${tau}
num_edge_loss_weight: 1.0
action_net_node_aggr:
  _target_: torch_geometric.nn.MeanAggregation
  _partial_: true
action_net_cord_aggr:
  _target_: torch_geometric.nn.MeanAggregation
  _partial_: true
action_net_hidden_features: 50
action_net_activation: 
  _target_: torch.nn.SiLU
  _partial_: true