_target_: src.models.egnn.EGNNClassifier
input_features: 61
node_features: 30
edge_features: 1
hidden_features: 50
out_features: 30
num_layers: 3
act:
  _target_: torch.nn.SiLU
  _partial_: true
optimizer: ${optimizer}
# lr_scheduler: ${lr_scheduler}
batch_size: ${batch_size}
dropout: 0.0
segmentation_loss:
  _target_: src.utils.losses.DiceLoss
segmentation_loss_weight: 1.0
node_aggr:
  _target_: torch_geometric.nn.SumAggregation
  _partial_: true
cord_aggr:
  _target_: torch_geometric.nn.MeanAggregation
  _partial_: true
embedding_size_atom: 30
num_embeddings_atom: 6
embedding_size_res: 30
num_embeddings_res: 21
dcc_threshold: 4
residual: true
update_coords: true
norm_coords: true
norm_coors_scale_init: 0.01
norm_feats: true
weight_share: false
