defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog
  - override launcher: submitit_slurm

launcher:
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  partition: gpu
  account: ${oc.env:SLURM_ACCOUNT}
  qos: default
  cpus_per_task: 1
  tasks_per_node: 4
  nodes: 1
  timeout_min: 480 
  setup:
    - cd ${oc.env:PROJECT_PATH}
    - source activate vnegnn
    - export HYDRA_FULL_ERROR=1
    - export WANDB_BASE_URL=${oc.env:WANDB_BASE_URL}