_target_: src.datasets.binding_dataset.BindingDataModuleHetero
train_dataloader:
  _target_: torch_geometric.loader.dataloader.DataLoader
  batch_size: ${batch_size}
  shuffle: true
  num_workers: ${num_workers}
  pin_memory: true
  dataset:
    _target_: src.datasets.binding_dataset.BindingDataset
    graph_builder:
      _target_: src.utils.graph.HeteroGraphBuilder
      _partial_: true
      esm_features: ${esm_features}
      max_neighbours: ${max_neighbours}
      neigh_dist_cutoff: ${neigh_dist_cutoff}
      number_of_global_nodes: ${number_of_global_nodes}
    root: data/scpdb/scpdb_subset_puresnet
    complex_names_path: data/scpdb/scpdb_subset_puresnet/scpdb_subset_puresnet_complex_names_train
    label: train
    random_rotations: ${random_rotations}
    global_node_subsample_size: ${global_node_subsample_size}
    debug: ${debug}
val_dataloader:
  _target_: torch_geometric.loader.dataloader.DataLoader
  batch_size: ${batch_size}
  shuffle: false
  num_workers: ${num_workers}
  pin_memory: true
  dataset:
    _target_: src.datasets.binding_dataset.BindingDataset
    graph_builder:
      _target_: src.utils.graph.HeteroGraphBuilder
      _partial_: true
      esm_features: ${esm_features}
      max_neighbours: ${max_neighbours}
      neigh_dist_cutoff: ${neigh_dist_cutoff}
      number_of_global_nodes: ${number_of_global_nodes}
    root: data/scpdb/scpdb_subset_puresnet
    complex_names_path: data/scpdb/scpdb_subset_puresnet/scpdb_subset_puresnet_complex_names_valid
    label: valid
    global_node_subsample_size: ${global_node_subsample_size}
    debug: ${debug}
test_dataloader_pdbbind2020:
  _target_: torch_geometric.loader.dataloader.DataLoader
  batch_size: ${batch_size}
  shuffle: true
  num_workers: ${num_workers}
  pin_memory: True
  dataset:
    _target_: src.datasets.binding_dataset.BindingDataset
    root: data/bindingsite_test_data/pdbbind2020
    complex_names_path: data/bindingsite_test_data/pdbbind2020/pdbbind2020_complex_names
    graph_builder:
      _target_: src.utils.graph.HeteroGraphBuilder
      _partial_: true
      esm_features: ${esm_features}
      max_neighbours: ${max_neighbours}
      neigh_dist_cutoff: ${neigh_dist_cutoff}
      number_of_global_nodes: ${number_of_global_nodes}
    label: test
    global_node_subsample_size: ${global_node_subsample_size}
    debug: ${debug}
test_dataloader_coach420:
  _target_: torch_geometric.loader.dataloader.DataLoader
  batch_size: ${batch_size}
  shuffle: False
  num_workers: ${num_workers}
  pin_memory: true
  dataset:
    _target_: src.datasets.binding_dataset.BindingDataset
    graph_builder:
      _target_: src.utils.graph.HeteroGraphBuilder
      _partial_: true
      esm_features: ${esm_features}
      max_neighbours: ${max_neighbours}
      neigh_dist_cutoff: ${neigh_dist_cutoff}
      number_of_global_nodes: ${number_of_global_nodes}
    root: data/bindingsite_test_data/coach420
    complex_names_path: data/bindingsite_test_data/coach420/coach420_complex_names
    label: test
    global_node_subsample_size: ${global_node_subsample_size}
    debug: ${debug}
test_dataloader_holo4k:
  _target_: torch_geometric.loader.dataloader.DataLoader
  batch_size: ${batch_size}
  shuffle: False
  num_workers: ${num_workers}
  pin_memory: true
  dataset:
    _target_: src.datasets.binding_dataset.BindingDataset
    graph_builder:
      _target_: src.utils.graph.HeteroGraphBuilder
      _partial_: true
      esm_features: ${esm_features}
      max_neighbours: ${max_neighbours}
      neigh_dist_cutoff: ${neigh_dist_cutoff}
      number_of_global_nodes: ${number_of_global_nodes}
    root: data/bindingsite_test_data/holo4k
    complex_names_path: data/bindingsite_test_data/holo4k/holo4k_complex_names
    label: test
    global_node_subsample_size: ${global_node_subsample_size}
    debug: ${debug}
# test_dataloader_holo4k_single:
#   _target_: torch_geometric.loader.dataloader.DataLoader
#   batch_size: ${batch_size}
#   shuffle: False
#   num_workers: ${num_workers}
#   pin_memory: true
#   dataset:
#     _target_: src.datasets.binding_dataset.BindingDataset
#     graph_builder:
#       _target_: src.utils.graph.HeteroGraphBuilder
#       _partial_: true
#       esm_features: ${esm_features}
#       max_neighbours: ${max_neighbours}
#       neigh_dist_cutoff: ${neigh_dist_cutoff}
#       number_of_global_nodes: ${number_of_global_nodes}
#     root: data/bindingsite_test_data/holo4k_split_chain
#     complex_names_path: data/bindingsite_test_data/holo4k_split_chain/holo4k_split_chain_complex_names
#     label: test
#     global_node_subsample_size: ${global_node_subsample_size}
#     debug: ${debug}